use super::*;
use tauri_plugin_dialog::{DialogExt, FilePath};

#[tauri::command]
pub fn list_history(core: CoreState<'_>) -> Result<Vec<DictationSession>, String> {
    core.list_history().map_err(|e| e.to_string())
}

#[tauri::command]
pub fn delete_history_entry(core: CoreState<'_>, id: String) -> Result<(), String> {
    if !is_valid_session_id(&id) {
        return Err("invalid session id".into());
    }
    if core
        .snapshot()
        .dictation
        .session_id
        .is_some_and(|active| active.to_string() == id)
    {
        return Err("cannot delete the active recording; stop or cancel it first".into());
    }
    core.delete_history(&id).map_err(|e| e.to_string())?;
    remove_recording_files(&id);
    Ok(())
}

#[tauri::command]
pub fn clear_history(core: CoreState<'_>) -> Result<(), String> {
    if core.snapshot().dictation.session_id.is_some() {
        return Err("cannot clear history while a recording is active".into());
    }
    let entries = core.list_history().map_err(|e| e.to_string())?;
    core.clear_history().map_err(|e| e.to_string())?;
    for entry in entries {
        if entry.source != openless_core::HistorySource::QuickNote {
            remove_recording_files(&entry.id);
        }
    }
    Ok(())
}

/// Daily activity summary (ascending by date); data source for the overview
/// page's yearly heatmap and the "last 7 / 30 days" metrics.
/// Decoupled from history content / retention: clearing history does not
/// affect it, the whole year's cells stay lit, and period statistics are not
/// truncated by the 200-entry history cap.
#[tauri::command]
pub fn get_activity_stats(core: CoreState<'_>) -> Vec<ActivityDay> {
    core.list_activity()
        .expect("activity snapshot should only fail after a poisoned lock")
}

fn recording_path_candidates(session_id: &str) -> Result<[std::path::PathBuf; 2], String> {
    if !is_valid_session_id(session_id) {
        return Err("invalid session id".into());
    }
    Ok([
        crate::persistence::recording_path_for_session(session_id).map_err(|e| e.to_string())?,
        crate::persistence::quick_note_recording_path_for_session(session_id)
            .map_err(|e| e.to_string())?,
    ])
}

fn existing_recording_path(session_id: &str) -> Result<std::path::PathBuf, String> {
    let candidates = recording_path_candidates(session_id)?;
    candidates
        .into_iter()
        .find(|path| path.is_file())
        .ok_or_else(|| "recording not found".to_string())
}

fn remove_recording_files(session_id: &str) {
    if let Ok(candidates) = recording_path_candidates(session_id) {
        for path in candidates {
            let _ = std::fs::remove_file(path);
        }
    }
}

/// Reads a session's raw microphone wav bytes. The file exists when: the user
/// is a debug user (any session), or the session failed with "transcribe
/// failed / empty" (failures are kept) — successful non-debug recordings are
/// deleted after insertion.
/// Naming convention: `<data_dir>/recordings/<session_id>.wav`, same name as
/// DictationSession.id.
///
/// Path validation: session_id **must** strictly match a UUID-v4 literal
/// (36 chars = 8-4-4-4-12 plus 4 `-`, content only ASCII hex + `-`).
/// Whitelist beats blacklist — absolute path prefixes, Windows ADS,
/// percent-encoding, and NUL bytes are all outside the legal charset, blocking
/// every Path::join escape. In-repo, session_id is generated by
/// `Uuid::new_v4()` (`dictation.rs:1531`) and the frontend only echoes back ids
/// it was given, but IPC = boundary, so it is validated strictly per boundary
/// rules.
///
/// Returns the recording as a base64 data URL the frontend plays directly via
/// `<audio src={url}>`.
///
/// The earlier implementation returned `Vec<u8>`, which Tauri IPC JSON-encoded
/// as a number array (~460 KB); in WebKit/Wry `<audio>` sometimes failed to
/// parse that Blob (zero duration, dead export). With a base64 data URL:
/// - the IPC payload grows only 33% (~150 KB), still safe
/// - the frontend needs no `ArrayBuffer → Blob → createObjectURL` chain
/// - the export button sets the data URL as `<a>.href` to trigger a download
#[tauri::command]
pub async fn read_audio_recording(session_id: String) -> Result<String, String> {
    if !is_valid_session_id(&session_id) {
        return Err("invalid session id".into());
    }
    let path = existing_recording_path(&session_id)?;
    let data = tokio::fs::read(&path).await.map_err(|e| {
        if e.kind() == std::io::ErrorKind::NotFound {
            "recording not found".into()
        } else {
            format!("read wav failed: {e}")
        }
    })?;
    log::info!(
        "[history] read_audio_recording id={session_id} bytes={} head={:?}",
        data.len(),
        &data.get(..16)
    );
    let b64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &data);
    let data_url = format!("data:audio/wav;base64,{b64}");
    log::info!(
        "[history] read_audio_recording data_url_len={}",
        data_url.len()
    );
    Ok(data_url)
}

/// Exports an archived recording wav to a user-selected path.
///
/// The backend opens the system save dialog directly; the path never travels
/// over IPC, so it cannot be tampered with or injected. The dialog call runs
/// in spawn_blocking to avoid blocking the Tauri async thread pool.
#[tauri::command]
pub async fn export_audio_recording(
    app: tauri::AppHandle,
    core: CoreState<'_>,
    session_id: String,
) -> Result<String, String> {
    if !is_valid_session_id(&session_id) {
        return Err("invalid session id".into());
    }

    // The quick-note export directory applies only to quick_note; regular
    // history entries keep the per-save dialog, so a directory configured in
    // quick notes cannot silently change export behavior for other history.
    let is_quick_note = core
        .list_history()
        .map(|entries| {
            entries.into_iter().any(|entry| {
                entry.id == session_id && entry.source == openless_core::HistorySource::QuickNote
            })
        })
        .unwrap_or(false);
    let configured_directory = if is_quick_note {
        core.get_preferences()
            .quick_note_export_directory
            .trim()
            .to_string()
    } else {
        String::new()
    };

    tokio::task::spawn_blocking(move || -> Result<String, String> {
        let src = existing_recording_path(&session_id)?;

        if configured_directory.is_empty() {
            let file_path = app
                .dialog()
                .file()
                .add_filter("WAV audio", &["wav"])
                .set_file_name(format!("openless-recording-{session_id}.wav"))
                .blocking_save_file();

            let Some(file_path) = file_path else {
                return Err("user cancelled".into());
            };

            return export_recording_to_destination(&app, file_path, &src);
        }

        let directory = std::path::PathBuf::from(configured_directory);
        std::fs::create_dir_all(&directory).map_err(export_recording_failed)?;
        let destination = directory.join(format!("openless-recording-{session_id}.wav"));
        copy_recording_to_path(&src, &destination)?;
        Ok(destination.to_string_lossy().into_owned())
    })
    .await
    .map_err(|e| format!("internal error: {e}"))?
}

fn export_recording_to_destination(
    app: &tauri::AppHandle,
    file_path: FilePath,
    source: &std::path::Path,
) -> Result<String, String> {
    #[cfg(target_os = "android")]
    if let FilePath::Url(url) = &file_path {
        if url.scheme() == "content" {
            copy_recording_to_mobile_url(app, &file_path, source)?;
            return Ok(url.to_string());
        }
    }

    #[cfg(target_os = "ios")]
    if let FilePath::Url(url) = &file_path {
        if url.scheme() == "file" {
            copy_recording_to_mobile_url(app, &file_path, source)?;
            return Ok(url.to_string());
        }
    }

    let destination = file_path.into_path().map_err(export_recording_failed)?;
    copy_recording_to_path(source, &destination)?;
    Ok(destination.to_string_lossy().into_owned())
}

const RECORDING_EXPORT_FAILED: &str = "recording export failed";

fn open_recording_source(source: &std::path::Path) -> Result<std::fs::File, String> {
    std::fs::File::open(source).map_err(|error| {
        if error.kind() == std::io::ErrorKind::NotFound {
            "recording not found".to_string()
        } else {
            export_recording_failed(error)
        }
    })
}

fn export_recording_failed(error: impl std::fmt::Display) -> String {
    log::error!("[history] audio recording export failed: {error}");
    RECORDING_EXPORT_FAILED.to_string()
}

fn copy_recording_to_path(
    source: &std::path::Path,
    destination: &std::path::Path,
) -> Result<(), String> {
    let mut source_file = open_recording_source(source)?;
    let mut destination_file =
        std::fs::File::create(destination).map_err(export_recording_failed)?;
    std::io::copy(&mut source_file, &mut destination_file)
        .map(|_| ())
        .map_err(export_recording_failed)
}

#[cfg(any(target_os = "android", target_os = "ios"))]
fn copy_recording_to_mobile_url(
    app: &tauri::AppHandle,
    destination: &FilePath,
    source: &std::path::Path,
) -> Result<(), String> {
    use tauri_plugin_fs::{FsExt, OpenOptions};

    let mut source_file = open_recording_source(source)?;
    let mut options = OpenOptions::new();
    options.write(true).truncate(true).create(true);
    let mut destination_file = match app.fs().open(destination.clone(), options) {
        Ok(file) => file,
        Err(error) => {
            #[cfg(target_os = "ios")]
            let _ = app
                .fs()
                .stop_accessing_security_scoped_resource(destination.clone());
            return Err(export_recording_failed(error));
        }
    };

    let copy_result = std::io::copy(&mut source_file, &mut destination_file)
        .map(|_| ())
        .map_err(export_recording_failed);

    #[cfg(target_os = "ios")]
    let stop_result = app
        .fs()
        .stop_accessing_security_scoped_resource(destination.clone())
        .map_err(export_recording_failed);

    if let Err(error) = copy_result {
        #[cfg(target_os = "ios")]
        let _ = stop_result;
        return Err(error);
    }

    #[cfg(target_os = "ios")]
    stop_result?;
    Ok(())
}

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HistoryRetranscriptionResult {
    text: String,
    updated_entry: Option<DictationSession>,
}

fn should_replace_failed_history(error_code: Option<&str>) -> bool {
    matches!(error_code, Some("transcribeFailed" | "emptyTranscript"))
}

/// Re-transcribes a history entry that has an archived recording using the
/// **current** ASR provider (issue #613 / #1046).
///
/// Flow: read `recordings/<id>.wav` → take PCM (skip the 44-byte WAV header) →
/// re-transcribe with the current provider → failed entries are repaired in
/// place; completed / polish-failed entries only get a temporary result and
/// never overwrite recorded history.
///
/// Re-transcribes audio only, no LLM polish. On failure the history and the
/// recording are untouched; the error returns to the frontend so the user can
/// retry.
#[tauri::command]
pub async fn retranscribe_recording(
    core: CoreState<'_>,
    session_id: String,
) -> Result<HistoryRetranscriptionResult, String> {
    if !is_valid_session_id(&session_id) {
        return Err("invalid session id".into());
    }
    let entry = core
        .list_history()
        .map_err(|e| e.to_string())?
        .into_iter()
        .find(|entry| entry.id == session_id)
        .ok_or_else(|| "history entry not found".to_string())?;
    if core
        .snapshot()
        .dictation
        .session_id
        .is_some_and(|active| active.to_string() == session_id)
    {
        return Err("recording is still active; stop it before retranscribing".into());
    }
    if entry.has_audio_recording != Some(true) {
        return Err("history entry has no archived recording".into());
    }
    if entry.pipeline_mode.as_deref() == Some("multimodal")
        && entry.source != openless_core::HistorySource::QuickNote
    {
        return Err("multimodal history does not support retranscription".into());
    }
    let path = existing_recording_path(&session_id)?;
    let wav = tokio::fs::read(&path).await.map_err(|e| {
        if e.kind() == std::io::ErrorKind::NotFound {
            "recording not found".into()
        } else {
            format!("read wav failed: {e}")
        }
    })?;
    // The archived wav is 16k/mono/16-bit with a fixed 44-byte standard header
    // (see asr::wav::encode_wav_16k_mono).
    if wav.len() <= 44 {
        return Err("recording is empty or corrupt".into());
    }
    let pcm = wav[44..].to_vec();

    let retranscribe_started = std::time::Instant::now();
    let retranscription = core
        .services()
        .auxiliary
        .retranscribe_pcm(pcm)
        .await
        .map_err(openless_core::RetranscriptionFailure::into_message)?;
    let text = retranscription.text;
    let asr_call_label = retranscription.asr;
    if text.trim().is_empty() {
        return Err("重新转录仍未识别到语音".into());
    }
    let retranscribe_ms = retranscribe_started.elapsed().as_millis() as u64;

    let updated_entry = if should_replace_failed_history(entry.error_code.as_deref())
        || entry.error_code.as_deref() == Some("recording")
        || entry.source == openless_core::HistorySource::QuickNote
    {
        Some(
            core.apply_history_retranscription(
                &session_id,
                text.clone(),
                &asr_call_label,
                retranscribe_ms,
            )
            .map_err(|e| e.to_string())?,
        )
    } else {
        None
    };
    Ok(HistoryRetranscriptionResult {
        text,
        updated_entry,
    })
}

#[tauri::command]
pub fn apply_quick_note_repolish(
    core: CoreState<'_>,
    session_id: String,
    text: String,
    style_pack_id: Option<String>,
) -> Result<DictationSession, String> {
    if !is_valid_session_id(&session_id) {
        return Err("invalid session id".into());
    }
    core.apply_history_repolish(&session_id, text, style_pack_id)
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod retranscription_tests {
    use super::{recording_path_candidates, should_replace_failed_history};

    #[test]
    fn recording_paths_reject_non_session_ids() {
        assert!(recording_path_candidates("../../victim").is_err());
        assert!(recording_path_candidates("not-a-session").is_err());
    }

    #[test]
    fn only_failed_transcriptions_are_replaced() {
        assert!(should_replace_failed_history(Some("transcribeFailed")));
        assert!(should_replace_failed_history(Some("emptyTranscript")));
        assert!(!should_replace_failed_history(Some("polishFailed")));
        assert!(!should_replace_failed_history(None));
    }
}
